name: Update

on:
  push:
    paths:
      - '.github/workflows/update.yml'
      - 'scripts/*.ts'
      - 'src/methods/**'
      - 'src/constants.ts'
      - 'src/utils.ts'
    branches:
      - 'master'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Update tables
        run: yarn tables

      - name: Update methods responses
        run: yarn methods
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: 🤖 Update tables and method responses'
          committer_name: GitHub Actions
          committer_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
